name: text_gen
description: Randomize your text
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0-182.1.beta <3.0.0'

dependencies:
  uuid: ^3.0.6
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  mutation_test: ^1.3.1
  test: ^1.21.4
  very_good_analysis: 3.0.1
